name: nereadaw

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        default: deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # CLONACIÓN DEL REPOSITORIO
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        
      # CREDENCIALES DE AWS
      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      # TERRAFORM INSTALL
      - name: Setup terraform
        run: |
          cd tf
          curl -Lo terraform.zip https://releases.hashicorp.com/terraform/1.4.0/terraform_1.4.0_linux_amd64.zip
          unzip -o terraform.zip
          sudo mv terraform /usr/local/bin/
          terraform --version

      # TERRAFORM INIT
      - name: TERRAFORM INIT
        run: |
          terraform init

      # TERRAFORM APPLY
      - name: TERRAFORM APPLY
        run: |
          terraform apply -auto-approve

        
